## Configuration File

[core]
## The site title will be shown on ever page on the right side of the logo.
# siteTitle = "My App"

## The company name is shown in the browser title bar. It can also be used with
## a modified template to show in the header.
# siteCompanyName = ""

## The site domain name. It must include the port if not normal http/https
## Example: wifi.example.com  OR  wifi.example.com:5000
# siteDomainName = ""

## This text will show up in the footer of every page
# siteFooterText = "App Footer"

[logging]
## Enable or disable normal application logging.
enabled = true

## Enable to disable web server logging. The log format is very similar to Apache.
enableHTTP = false

## Lowest level to log. Recommended to be information in dev/testing and notice in prod.
## Standard syslog levels plus fatal.
level = "debug"

## File path or directory to store log files. If a directory is given, each log level
## will be outputted to its own file. If path is an empty string, logs will not be written
## to disk.
path = ""

[database]
## Supported database types are: sqlite
type = "sqlite"

## The address, socket, or filename of the database
address = "database.sqlite3"

# Port, not needed for SQLite, defaults to database-specific default port
# port = 0

## Username of database
# username = ""

## Password of database
# password = ""

## Name of the database to use, not needed for SQLite
# name = ""

## Number of connection retries before failing. 0 means retry indefinitly
# retry = 0

## Timeout before the next connection retry
# retryTimeout = "1m"

[webserver]
## IP address to listen on. Leave blank to listen on all addresses.
address = ""

## Plain HTTP port to listen on
httpPort = 8080

## Encrypted HTTP port to listen on, if the TLS settings are blank, HTTPS will not start
httpsPort = 1443

## TLS Certificate, must be concatentated with all intermediate certificates
# TLSCertFile = ""

## Private key file for main certificate
# TLSKeyFile = ""

## Enable/disable HTTP redirect to HTTPS
# redirectHttpToHttps = false

## SessionStore is how sessions will be stored.
## Valid values: filesystem, database
# sessionStore = "database"

## The name given to the cookie on the client that stores a session token
sessionName = "app"

## Directory path to store session data
sessionsDir = "sessions"

# This is the authentication key for web sessions. Make sure this is unique and protected.
sessionsAuthKey = "change me please"

# Key to use when encrypting session data server-side. Optional.
# Should be 16, 24, or 32 characters long.
# sessionsEncryptKey = ""
